# Generated by Django 6.0 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('troisieme', '3ème (Brevet)'), ('terminale', 'Terminale (BAC)')], max_length=20, verbose_name='Niveau')),
                ('serie', models.CharField(blank=True, choices=[('general', 'Général'), ('A', 'Série A (Littéraire)'), ('C', 'Série C (Scientifique)'), ('D', 'Série D (Scientifique)'), ('E', 'Série E (Économique)')], max_length=20, verbose_name='Série')),
                ('nb_eleves', models.PositiveIntegerField(default=0, verbose_name="Nombre d'élèves")),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'classe',
                'ordering': ['niveau', 'serie'],
                'indexes': [models.Index(fields=['niveau'], name='classe_niveau_673396_idx')],
                'unique_together': {('niveau', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(choices=[('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('FR', 'Français')], default='MATH', max_length=20, verbose_name='Nom de la matière')),
                ('classes_matieres', models.ManyToManyField(to='cora_core.classe', verbose_name='CLASSE_MATIERES')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'matiere',
                'ordering': ['nom_matiere'],
            },
        ),
    ]
