# Generated by Django 6.0 on 2026-01-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cora_core', '0002_rename_classe_niveau_673396_idx_aaclasse_niveau_3d04ab_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classe',
            new_name='classe_niveau_673396_idx',
            old_name='aaclasse_niveau_3d04ab_idx',
        ),
        migrations.AlterModelTable(
            name='classe',
            table='classe',
        ),
    ]
