# Generated by Django 6.0 on 2026-01-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cora_core', '0004_alter_classe_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objectif_pedagogique', models.TextField(blank=True)),
                ('duree_totale', models.PositiveIntegerField(blank=True, null=True)),
                ('est_verrouille', models.BooleanField(default=False)),
                ('est_publie', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='cora_core.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='cora_core.matiere')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'db_table': 'cours',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('numero', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='cora_core.cours')),
            ],
            options={
                'verbose_name': 'chapitre',
                'verbose_name_plural': 'chapitres',
                'db_table': 'chapitre',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points_max', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duree_estimee', models.PositiveIntegerField(default=0)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='quiz/')),
                ('chapitre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cora_core.chapitre')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cora_core.cours')),
            ],
            options={
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_ressource', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('url_video', models.URLField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('duree', models.PositiveIntegerField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('est_publie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='cora_core.chapitre')),
            ],
            options={
                'db_table': 'ressource',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reponses', models.JSONField(null=True)),
                ('est_termine', models.BooleanField(default=False)),
                ('temps_total_passe', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to='accounts.eleve')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cora_core.quiz')),
            ],
            options={
                'db_table': 'tentative_quiz',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_progression', models.PositiveIntegerField(default=0)),
                ('est_termine', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('temps_total_passe', models.PositiveIntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='cora_core.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='accounts.eleve')),
            ],
            options={
                'db_table': 'progression_eleve',
                'constraints': [models.UniqueConstraint(fields=('eleve', 'cours'), name='unique_progression_eleve_cours')],
            },
        ),
    ]
