# Generated by Django 6.0 on 2026-01-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cora_core', '0005_cours_chapitre_quiz_ressource_tentativequiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressource',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='est_publie',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='titre',
        ),
    ]
