# Generated by Django 6.0 on 2026-01-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cora_core', '0006_alter_ressource_options_remove_ressource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='colorBg',
            field=models.CharField(default='bg-blue-500', max_length=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='matiere_icon'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matiere_img'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='prochainCours',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='progressColor',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='progression',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='statusColor',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
