# Generated by Django 6.0 on 2026-02-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cora_core', '0007_matiere_colorbg_matiere_icon_matiere_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='classe',
        ),
    ]
