# Generated by Django 6.0 on 2026-01-03 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cora_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide (format: +225XXXXXXXX)', regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profils/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('enseignant', 'Enseignant'), ('eleve', 'Élève')], default='eleve', max_length=20, verbose_name='Rôle')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telephone'], name='user_telepho_5220d7_idx'), models.Index(fields=['role'], name='user_role_3744fd_idx'), models.Index(fields=['est_actif'], name='user_est_act_d62ff5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField(blank=True, help_text="Présentation de l'enseignant", verbose_name='Biographie')),
                ('etablissement', models.CharField(blank=True, help_text='Établissement de rattachement', max_length=200, verbose_name='Établissement')),
                ('nb_cours_publies', models.PositiveIntegerField(default=0, verbose_name='Nombre de cours publiés')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, help_text='Note moyenne des cours (sur 5)', max_digits=3, verbose_name='Note moyenne')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to='accounts.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignant',
                'ordering': ['-note_moyenne', '-nb_cours_publies'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droits_speciaux', models.JSONField(blank=True, default=list, help_text="Liste des permissions spéciales de l'admin", verbose_name='Droits spéciaux')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_admin', to='accounts.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('gratuit', 'Gratuit'), ('premium', 'Premium')], default='gratuit', max_length=20, verbose_name="Statut d'abonnement")),
                ('points_xp', models.PositiveIntegerField(default=0, help_text="Points d'expérience pour la gamification", verbose_name='Points XP')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('streak_jours', models.PositiveIntegerField(default=0, help_text='Nombre de jours consécutifs de connexion', verbose_name='Série de jours consécutifs')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='cora_core.classe', verbose_name='Classe')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_eleve', to='accounts.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'db_table': 'eleve',
                'ordering': ['-points_xp'],
                'indexes': [models.Index(fields=['statut'], name='eleve_statut_ff66e1_idx'), models.Index(fields=['classe'], name='eleve_classe__1497a6_idx'), models.Index(fields=['-points_xp'], name='eleve_points__8a7c83_idx')],
            },
        ),
    ]
